const REACT = 'REACT';
const UNREACT = 'UNREACT';
const MARK_TODO = 'MARK_TODO';
const ADD_RESPONSE = 'ADD_RESPONSE';

const PATCH_TYPES = [REACT, UNREACT, MARK_TODO, ADD_RESPONSE];

const CONTENT_CARD = 'CONTENT_CARD';
const QUESTION_CARD = 'QUESTION_CARD';

const CARD_TYPES = [CONTENT_CARD, QUESTION_CARD];

const TEXT_CONTENT = 'TEXT';
const CHART_CONTENT = 'CHART';
const IMAGE_CONTENT = 'IMAGE';
const VIDEO_CONTENT = 'VIDEO';
const SERIAL_TABLE_CONTENT = 'SERIAL_TABLE';
const SCHEDULED_CONTENT = 'SCHEDULED_CONTENT';
const TODO_CONTENT = 'TODO_CONTENT';

const CONTENT_CARD_TYPES = [
  TEXT_CONTENT,
  CHART_CONTENT,
  IMAGE_CONTENT,
  VIDEO_CONTENT,
  SERIAL_TABLE_CONTENT,
  SCHEDULED_CONTENT,
  TODO_CONTENT,
];

const INDIVIDUAL_TYPE = 'INDIVIDUAL';
const TEAM_TYPE = 'TEAM';

const MULTIPLE_CHOICE_QUESTION = 'MULTIPLE_CHOICE';
const MULTIPLE_RESPONSE_CONTENT = 'multipleChoiceContent';

const LIKERT_QUESTION = 'LIKERT';
const LIKERT_RESPONSE_CONTENT = 'likertContent';

const COLUMN_ORDERING_QUESTION = 'COLUMN_ORDERING';
const COLUMN_ORDERING_RESPONSE_CONTENT = 'columnReorderingContent';

const OPEN_TEXT_QUESTION = 'OPEN_TEXT';
const OPEN_TEXT_RESPONSE_CONTENT = 'openTextContent';

const QUESTION_CONTENT_RESPONSE_MAPPING = {
  [MULTIPLE_CHOICE_QUESTION]: MULTIPLE_RESPONSE_CONTENT,
  [LIKERT_QUESTION]: LIKERT_RESPONSE_CONTENT,
  [COLUMN_ORDERING_QUESTION]: COLUMN_ORDERING_RESPONSE_CONTENT,
  [OPEN_TEXT_QUESTION]: OPEN_TEXT_RESPONSE_CONTENT,
};

const QUESTION_CARD_TYPES = [
  MULTIPLE_CHOICE_QUESTION,
  LIKERT_QUESTION,
  COLUMN_ORDERING_QUESTION,
  OPEN_TEXT_QUESTION,
];

const DONE_STATUS = 'DONE';
const STUCK_STATUS = 'STUCK';

const TODO_STATUS = [DONE_STATUS, STUCK_STATUS];

const SCHEDULED_TODO_TYPES = [INDIVIDUAL_TYPE, TEAM_TYPE];

const UNDERSTOOD = 'UNDERSTOOD';
const EXCITED = 'EXCITED';
const BORED = 'BORED';
const CONFUSED = 'CONFUSED';

const REACTION_TYPES = [UNDERSTOOD, EXCITED, BORED, CONFUSED];

export {
  CARD_TYPES,
  CONTENT_CARD,
  QUESTION_CARD,
  CONTENT_CARD_TYPES,
  TEXT_CONTENT,
  CHART_CONTENT,
  IMAGE_CONTENT,
  VIDEO_CONTENT,
  SERIAL_TABLE_CONTENT,
  SCHEDULED_CONTENT,
  TODO_CONTENT,
  INDIVIDUAL_TYPE,
  TEAM_TYPE,
  SCHEDULED_TODO_TYPES,
  QUESTION_CARD_TYPES,
  MULTIPLE_CHOICE_QUESTION,
  LIKERT_QUESTION,
  COLUMN_ORDERING_QUESTION,
  OPEN_TEXT_QUESTION,
  TODO_STATUS,
  DONE_STATUS,
  STUCK_STATUS,
  REACT,
  UNREACT,
  MARK_TODO,
  ADD_RESPONSE,
  PATCH_TYPES,
  QUESTION_CONTENT_RESPONSE_MAPPING,
  UNDERSTOOD,
  BORED,
  EXCITED,
  CONFUSED,
  REACTION_TYPES,
};
