const EMPLOYEE_ROLE = 'EMPLOYEE';
const SUPERVISOR_ROLE = 'SUPERVISOR';
const ADMINISTRATOR_ROLE = 'ADMINISTRATOR';

const USER_ROLES = [EMPLOYEE_ROLE, SUPERVISOR_ROLE, ADMINISTRATOR_ROLE];

export { EMPLOYEE_ROLE, SUPERVISOR_ROLE, ADMINISTRATOR_ROLE, USER_ROLES };
