const EMPLOYEE_ROLE = 'EMPLOYEE';
const SUPERVISOR_ROLE = 'SUPERVISOR';
const PROGRAM_ADMINISTRATOR_ROLE = 'PROGRAM ADMINISTRATOR';

const USER_ROLES = [EMPLOYEE_ROLE, SUPERVISOR_ROLE, PROGRAM_ADMINISTRATOR_ROLE];

const DONE_STATUS = 'DONE';
const STUCK_STATUS = 'STUCK';

const TODO_STATUS = [DONE_STATUS, STUCK_STATUS];

const PIN_USER = 'PIN_USER';
const UNPIN_USER = 'UNPIN_USER';

export {
  EMPLOYEE_ROLE,
  SUPERVISOR_ROLE,
  PROGRAM_ADMINISTRATOR_ROLE,
  USER_ROLES,
  DONE_STATUS,
  STUCK_STATUS,
  TODO_STATUS,
  PIN_USER,
  UNPIN_USER,
};
