const EMPLOYEE_ROLE = 'EMPLOYEE';
const SUPERVISOR_ROLE = 'SUPERVISOR';
const ADMINISTRATOR_ROLE = 'ADMINISTRATOR';

const USER_ROLES = [EMPLOYEE_ROLE, SUPERVISOR_ROLE, ADMINISTRATOR_ROLE];

const DONE_STATUS = 'DONE';
const STUCK_STATUS = 'STUCK';

const TODO_STATUS = [DONE_STATUS, STUCK_STATUS];

export {
  EMPLOYEE_ROLE,
  SUPERVISOR_ROLE,
  ADMINISTRATOR_ROLE,
  USER_ROLES,
  DONE_STATUS,
  STUCK_STATUS,
  TODO_STATUS,
};
